FROM python:3.12-slim

RUN apt-get update \
  && apt-get install -y libpq-dev gcc postgresql-client git

WORKDIR /oc4ids_datastore_pipeline

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN pip install -e .

ENTRYPOINT ["sleep", "infinity"]
