"""rename column license name to license title

Revision ID: 8182d8c386f7
Revises: 3499656b84e7
Create Date: 2025-02-25 15:40:01.727396

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8182d8c386f7"
down_revision: Union[str, None] = "3499656b84e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset", "license_name", nullable=True, new_column_name="license_title"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset", "license_title", nullable=True, new_column_name="license_name"
    )
    # ### end Alembic commands ###
