"""add publisher_country column

Revision ID: b21b5de6ee2d
Revises: ebb26242c904
Create Date: 2025-03-26 10:08:14.401880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b21b5de6ee2d"
down_revision: Union[str, None] = "ebb26242c904"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("publisher_country", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset", "publisher_country")
    # ### end Alembic commands ###
