"""add_portals

Revision ID: cde761a59c2f
Revises: b21b5de6ee2d
Create Date: 2025-07-08 07:51:48.954914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde761a59c2f'
down_revision: Union[str, None] = 'b21b5de6ee2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('portal_url', sa.String(), nullable=True))
    op.add_column('dataset', sa.Column('portal_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'portal_title')
    op.drop_column('dataset', 'portal_url')
    # ### end Alembic commands ###
