"""add license_title_short column

Revision ID: ebb26242c904
Revises: 8182d8c386f7
Create Date: 2025-02-25 15:47:03.169950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebb26242c904"
down_revision: Union[str, None] = "8182d8c386f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dataset", sa.Column("license_title_short", sa.String(), nullable=True)
    )
    op.alter_column(
        "dataset", "license_title", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset", "license_title", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("dataset", "license_title_short")
    # ### end Alembic commands ###
