name: Create GitHub release

on:
  push:
    branches:
      - live

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install local package
        run: pip install .
      - name: Extract version
        run: |
          VERSION=$(python -c "import importlib.metadata; print(importlib.metadata.version('oc4ids-datastore-pipeline'))")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Print version
        run: echo $VERSION
      - name: Create tag
        run: |
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
      - name: Create release
        run: |
          gh release create "v${VERSION}" \
            --repo="${GITHUB_REPOSITORY}" \
            --title="v${VERSION}" \
            --generate-notes
